
logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

network: 'data/networks/elec_s_37_ec_lcopt_Co2L_h80.nc'

mga_slack: 0.2
mcmc_variables: 'all' # 'all' selects all 

sampler:
  chains: 4
  samples: 501 # has to be a multiple of 101
  eps: 500 # was 0.1  


solver:
  solver_name: 'gurobi'
  formulation: 'kirchhoff'
  pyomo: false
  solver_options:
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200

